### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by kamalkech** [beyonk-adventures/svelte-component-livereload-template#1]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^6.1.0" from the root project
npm ERR!   peer eslint@">= 3" from @beyonk/eslint-config@4.2.0
npm ERR!   node_modules/@beyonk/eslint-config
npm ERR!     dev @beyonk/eslint-config@"^4.0.1" from the root project
npm ERR!   4 more (eslint-config-standard, eslint-plugin-import, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">=7.0.0" from eslint-plugin-mocha@7.0.1
npm ERR! node_modules/@beyonk/eslint-config/node_modules/eslint-plugin-mocha
npm ERR!   eslint-plugin-mocha@"^7.0.1" from @beyonk/eslint-config@4.2.0
npm ERR!   node_modules/@beyonk/eslint-config
npm ERR!     dev @beyonk/eslint-config@"^4.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by antony** [comment]
Hi @kamalkech - you can use Vite or Snowpack to achieve the same thing now. This repository should be archived.
